name: Automated Upload to S3
 
on:
  push:
    branches: [ main ]
    paths:
    - '**.tex'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile into PDF and upload to S3
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-east-1"
        run: |
          sudo apt install texlive-latex-extra
          pdflatex -interaction=nonstopmode resume.tex | tail -n2 | head -1 | awk '/1 page/ {rc = 1}; END { exit !rc }'
          aws s3 cp resume.pdf s3://linkletter/public/Linkletter_Resume.pdf
